name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run eslint
      run: npm run lint

  playwright-tests:
    needs: eslint-check
    env:
      HOME: /root
      BASE_URL: ${{secrets.BASE_URL}}
      API_URL: ${{ secrets.API_URL }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
      CUSTOMER_EMAIL: ${{ secrets.CUSTOMER_EMAIL }}
      CUSTOMER_PASSWORD: ${{ secrets.CUSTOMER_PASSWORD }}
      CUSTOMER_USERNAME: ${{ vars.CUSTOMER_USERNAME }}

    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-jammy
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1,2,3]
        shardTotal: [3]
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Update Playwright snapshots
      run: npx playwright test --update-snapshots --project=screenshot-tests

    - name: Run Playwright tests
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1

  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [playwright-tests]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: blob-report-*
        merge-multiple: true

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7